name: risk
channels:
  - conda-forge
  - defaults
dependencies:
  # ============================================================
  # 평가 서버 환경 기준 (Ubuntu 22.04.5 LTS, Python 3.10.12)
  # 반드시 이 환경과 동일하게 유지해야 재현 가능
  # ============================================================
  - python=3.10.12

  # ============================================================
  # 평가 서버 기본 설치 패키지 (버전 정확히 일치)
  # requirements.txt에 포함하지 않음
  # ============================================================
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - pyyaml=6.0.2

  # ============================================================
  # 추가 설치 필요 패키지 (requirements.txt에 포함)
  # 평가 서버에 설치됨
  # ============================================================
  - xgboost=2.1.3        # CPU 최적화 버전
  - catboost=1.2.8

  # ============================================================
  # 개발용 도구 (평가 서버에는 없음, 로컬 개발용)
  # ============================================================
  - ipykernel=6.29.5
  - notebook=7.2.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - jupyter=1.1.1

  # 추가 개발 도구
  - pip=24.2

  # pip 패키지 (conda에서 설치 안되는 것들)
  - pip:
    - tqdm==4.66.5       # 평가 서버 기본 설치
    - loguru==0.7.2      # 평가 서버 기본 설치