random_seed: 42

paths:
  data_dir: data
  model_dir: model

columns:
  id: Test_id
  test: Test
  target: Label
  group: PrimaryKey
  age: Age
  date: TestDate

model:
  name: xgb
  type: xgb               # xgb or catboost
  per_test: true          # A/B 별 개별 모델
  params:
    # XGBoost parameters
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 8
    min_child_weight: 3    # Balanced value for minority class learning
    subsample: 0.9
    colsample_bytree: 0.9
    tree_method: hist      # Faster histogram-based algorithm
    random_state: 42
    n_jobs: -1
    verbosity: 0           # Reduce XGBoost logging
